name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
        with:
          repository: facebook/lexical

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install

      - name: Build
        run: ls node_modules | wc -l

